# fly.toml app configuration file generated for utube-nu-ten on 2025-01-14T23:13:52+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'utube-nu-ten'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
